### ISSUE TITLE
appsec.yaml wrong formating

### ISSUE THREAD

**Issue by elliotrock** [tqc/codedeploy-scripts#2]
Below works but the use of the + in yours was break AWS:

```
version: 0.0
os: linux
files:
    - source: /
      destination: /app/pennybox-core-api-app
hooks:
#  ApplicationStop:
#    - location: deployment.js
#      timeout: 180
  BeforeInstall:
    - location: deployment.js
      timeout: 180
  AfterInstall:
    - location: deployment.js
      timeout: 180
  ApplicationStart:
    - location: deployment.js
      timeout: 180
  ValidateService:
    - location: deployment.js
      timeout: 180
```
